### ISSUE TITLE
python3 import error

### ISSUE THREAD

**Issue by peercoinops** [peerchemist/peercoin_rpc#5]
pip3  install --user git+git://github.com/peerchemist/peercoin_rpc.git

python3

> > > import peercoin_rpc
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/ubuntu/.local/lib/python3.5/site-packages/peercoin_rpc/**init**.py", line 1, in <module>
> > >     from peercoin_rpc import Client
> > > ImportError: cannot import name 'Client'

**Comment by peerchemist** [comment]
Confirmed, will try to triage now.

**Comment by peerchemist** [comment]
Fixed with https://github.com/peerchemist/peercoin_rpc/commit/36aa7f4431985c4c43e5201d1e4a488152532e40
